donut/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
]

donuts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
]

haveadonut/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('donuts.urls')),
    url(r'^matt/', include(admin.site.urls)),
]

donuts/models.py
from django.db import models

class Chat(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    def __str__(self):
        return (self.first_name + ' ' + self.last_name)

class Donut(models.Model):
    donut_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date given')
    chat = models.ForeignKey(Chat)
    def __str__(self):
        return (self.chat.first_name+' - '+self.donut_text)

donuts/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Donut, Chat
from django.db.models import Count

def index(request):
    latest_donut_list = Donut.objects.order_by('-pub_date')[:10]
    best_chat_list = Chat.objects.annotate(donut_count=Count('donut')).order_by('-donut_count')[:10]
    context = {
        'latest_donut_list': latest_donut_list,
        'best_user_list': best_chat_list,
    }
    return render(request, 'donuts/index.html', context)

donuts/templates/donuts/index.html
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"> {% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'donuts/style.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'donuts/bootstrap.min.css' %}" />
<script src="{% static 'donuts/jquery.min.js' %}"></script>
<script src="{% static 'donuts/bootstrap.min.js' %}"></script>


<div class="container">
  <div class="page-header center" style="text-align:center">
    <h1>Here... have a donut!</h1>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-8">
      <img src="{% static 'donuts/images/cat.jpg' %}" width="100"></img>
      {% if best_user_list %}
      <div class="list-group">
        <div class="list-group-item">
          <h2 class="list-group-item-heading">Donut d'or : {{ best_user_list.0.first_name }} avec {{ best_user_list.0.donut_set.all.count }} donuts</h2>
          {% for donut in best_user_list.0.donut_set.all %}
          <img src="{% static 'donuts/images/donut.svg' %}" width="25"></img>
          {% endfor %}
        </div>
        <div class="list-group-item">
          <h3 class="list-group-item-heading">Donut d'argent : {{ best_user_list.1.first_name }} avec {{ best_user_list.1.donut_set.all.count }} donuts</h3>
          {% for donut in best_user_list.1.donut_set.all %}
          <img src="{% static 'donuts/images/donut.svg' %}" width="25"></img>
          {% endfor %}
        </div>
        <div class="list-group-item">
          <h4 class="list-group-item-heading">Donut de bronze : {{ best_user_list.2.first_name }} avec {{ best_user_list.2.donut_set.all.count }} donuts</h4>
          {% for donut in best_user_list.2.donut_set.all %}
          <img src="{% static 'donuts/images/donut.svg' %}" width="25"></img>
          {% endfor %}
        </div>
        {% for user in best_user_list %}
        {% if forloop.counter > 3 %}
        {% if user.donut_set.all.count != 0 %}
        <div class="list-group-item">
          <p class="list-group-item-text">{{ forloop.counter }}e : {{ user.first_name }} avec {{ user.donut_set.all.count }} donuts</p>
        </div>
        {% endif %}
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}
    </div>
    <div class="col-xs-12 col-md-4">
      <h3>Derniers donuts :</h3>
      {% if latest_donut_list %}
      <div class="list-group">
        {% for donut in latest_donut_list %}
        <a class="list-group-item" role="button" data-toggle="collapse" href="#latestCollapse{{ donut.id }}" aria-expanded="false" aria-controls="latestCollapse{{ donut.user.id }}">
          <span class="label label-default">{{ donut.pub_date|date:"d / m / Y" }}</span>
          {{ donut.chat.first_name }}
          <div class="collapse" id="latestCollapse{{ donut.id }}">
            {{ donut.donut_text }}
          </div>
        </a>
        {% endfor %}
      </div>
      {% else %}
      <p>Pas de nouveaux donuts...</p>
      {% endif %}
      </div>
    </div>

  </div>